name       : calcurse
version    : 4.2.2
release    : 1
source     :
    - http://calcurse.org/files/calcurse-4.2.2.tar.gz : c6881ddbd1cc7fbd02898187ac0fb4c6d8ac4c2715909b1cf00fb7a90cf08046
license    : BSD-2-Clause
component  : office
summary    : Calcurse is a calendar and scheduling application for the command line.
description: |
  Calcurse is a calendar and scheduling application for the command line. It helps keep track of events, appointments and everyday tasks. A configurable notification system reminds user of upcoming deadlines, the curses based interface can be customized to suit user needs and a very powerful set of command line options can be used to filter and format appointments, making it suitable for use in scripts.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
