name       : calcurse
version    : 4.8.1
release    : 10
source     :
    - https://calcurse.org/files/calcurse-4.8.1.tar.gz : d86bb37014fd69b8d83ccb904ac979c6b8ddf59ee3dbc80f5a274525e4d5830a
homepage   : https://calcurse.org/
license    : BSD-2-Clause
component  : office
summary    : Calcurse is a calendar and scheduling application for the command line
description: |
    Calcurse is a calendar and scheduling application for the command line. It helps keep track of events, appointments and everyday tasks. A configurable notification system reminds user of upcoming deadlines, the curses based interface can be customized to suit user needs and a very powerful set of command line options can be used to filter and format appointments, making it suitable for use in scripts.
builddeps  :
    - asciidoc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
