name       : calcurse
version    : 4.5.1
release    : 6
source     :
    - https://github.com/lfos/calcurse/archive/v4.5.1.tar.gz : 8cc46137b5e24dfd0c58ab8e91bcf7c8fad8c2336fc7591a4ea5e51d3a76543b
license    : BSD-2-Clause
component  : office
summary    : Calcurse is a calendar and scheduling application for the command line.
description: |
    Calcurse is a calendar and scheduling application for the command line. It helps keep track of events, appointments and everyday tasks. A configurable notification system reminds user of upcoming deadlines, the curses based interface can be customized to suit user needs and a very powerful set of command line options can be used to filter and format appointments, making it suitable for use in scripts.
builddeps  :
    - asciidoc
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
